#pragma once

#define V34_ART_VERSION_MAJOR 1
#define V34_ART_VERSION_MINOR 0
#define V34_ART_VERSION_PATCH 0
#define V34_ART_VERSION_BUILD 0

#define V34_ART_VERSION_FILE 1,0,0,0
#define V34_ART_VERSION_STRING "1.0"
#define V34_ART_DISTRIBUTION_BASENAME "v34_art_v1.0"

#define V34_ART_PRODUCT_NAME "CS:S V34 ADVANCED RECORDING TOOLS"
#define V34_ART_COMPANY_NAME "Contrastniy"
#define V34_ART_COPYRIGHT "Copyright (c) 2026 Contrastniy"
#define V34_ART_ICON_RESOURCE_ID 101
